services:
  postgres:
    container_name: ai-agent-postgres
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ai_agent_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  pgadmin:
    container_name: ai-agent-pgadmin
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

  prometheus:
    container_name: ai-agent-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - postgres
  
  grafana:
    container_name: ai-agent-grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    depends_on:
      - prometheus